#!/usr/bin/env bash

alias a="atom"
changeDir() {
	cd ~/Projects/$1
}

alias pr=changeDir

parse_git_branch() {
  git branch 2> /dev/null | sed -e '/^[^*]/d' -e 's/* \(.*\)/ (\1)/'
}

export PS1="\W\[\033[32m\]\$(parse_git_branch)\[\033[00m\] \[\033[35m\]$\[\033[00m\] "

PATH=$PATH:$(pwd)/.terminal/bin
